export default [
      {
        id:1,
        tag:'aa',
        name:'主粮',
        icon:'',
        dishs:[
          {
            id:1,
            price:89,
            name:'三文鱼',
            sales:12,
            pic:'swy.png',
            count:0
          },
          {
            id:2,
            price:10,
            name:'鲜肉粮',
            sales:18,
            pic:'xr.png',
            count:0
          },
          {
            id:3,
            price:30,
            name:'羊排',
            sales:36,
            pic:'xr.png',
            count:0
          }
        ]
      },
      {
        id:2,
        tag:'bb',
        name:'零食',
        icon:'',
        dishs:[
          {
            id:4,
            price:16,
            name:'饼干',
            sales:39,
            pic:'bg.png',
            count:0
          },
          {
            id:5,
            price:10,
            name:'酸醉蟹钳',
            sales:23,
            pic:'dish-6.jpg',
            count:0
          }
        ]
      },
      {
        id:3,
        tag:'cc',
        name:'日用',
        icon:'',
        dishs:[
          {
            id:6,
            price:26,
            name:'洁齿棒',
            sales:34,
            pic:'jc.png',
            count:0
          },
          {
            id:7,
            price:10,
            name:'清蒸草鱼',
            sales:38,
            pic:'dish-4.jpg',
            count:0
          }
        ]
      },
      {
        id:4,
        tag:'dd',
        name:'保健品',
        icon:'',
        dishs:[
          {
            id:8,
            price:16,
            name:'羊奶粉',
            sales:34,
            pic:'nf.png',
            count:0
          },
          {
            id:9,
            price:10,
            name:'关节膏',
            sales:12,
            pic:'gj.png',
            count:0
          }
        ]
      },
      {
        id:5,
        tag:'ff',
        name:'罐头',
        icon:'',
        dishs:[
          {
            id:10,
            price:16,
            name:'羊奶粉',
            sales:34,
            pic:'nf.png',
            count:0
          },
          {
            id:11,
            price:10,
            name:'关节膏',
            sales:12,
            pic:'gj.png',
            count:0
          }
        ]
      },
      {
        id:6,
        tag:'ee',
        name:'其他',
        icon:'',
        dishs:[
          {
            id:12,
            price:16,
            name:'羊奶粉',
            sales:34,
            pic:'nf.png',
            count:0
          },
          {
            id:13,
            price:10,
            name:'关节膏',
            sales:12,
            pic:'gj.png',
            count:0
          }
        ]
      }

    ]